"""password length

Revision ID: 283dcb4ffd3f
Revises: e7153efc39ff
Create Date: 2024-05-14 13:11:44.641527

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "283dcb4ffd3f"
down_revision = "e7153efc39ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=mysql.VARCHAR(length=100),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=255),
            type_=mysql.VARCHAR(length=100),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
